[project]
name = "plotsrv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.3",
    "matplotlib>=3.10.7",
    "plotnine>=0.15.1",
    "pytest>=9.0.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = ["seaborn>=0.13.2"]
