[project]
name = "plotsrv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "fastapi>=0.121.3",
    "httpx>=0.28.1",
    "matplotlib>=3.10.7",
    "plotnine>=0.15.1",
    "pytest>=9.0.1",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "seaborn>=0.13.2",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
]
